### ISSUE TITLE
Allow smaller increments in One-Click Tip Amount

### ISSUE THREAD

**Issue by JettScythe** [memberapp/server#5]
Using memo.cash I had it set to auto tip 1500 sats, but I noticed when trying to add that to the one click tip amount on member, it will not accept 1500 and says the two nearest valid values are 1000 and 2000

**Comment by FreeTrade** [comment]
That sounds undesirable - i guess it is because the increment makes the up/down arrows work better. I think it would be better to be able to set custom values and ditch the up/down increment step.

n.b. for issues for the client side of things - plz use
https://github.com/memberapp/memberapp.github.io/issues
